apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: zetterstrom-dev
build:
  local:
    push: false
  artifacts:
    - image: viktorzetterstrom/index-zetterstrom-dev
      context: index
      sync:
        infer:
          - "**/*.html"
          - "**/*.js"
          - "**/*.css"
    - image: viktorzetterstrom/shl-client-zetterstrom-dev
      context: shl/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: viktorzetterstrom/shl-api-zetterstrom-dev
      context: shl/api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: viktorzetterstrom/trivia-client-zetterstrom-dev
      context: trivia/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: viktorzetterstrom/trivia-api-zetterstrom-dev
      context: trivia/api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: viktorzetterstrom/movies-zetterstrom-dev
      context: movies
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.ts"
          - "**/*.css"
          - "**/*.html"
    - image: viktorzetterstrom/news-zetterstrom-dev
      context: news
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.ts"
          - "**/*.css"
          - "**/*.html"
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/index-depl.yaml
      - k8s/shl-client-depl.yaml
      - k8s/shl-api-depl.yaml
      - k8s/secrets/shl-api-secret.yaml
      - k8s/trivia-client-depl.yaml
      - k8s/trivia-api-depl.yaml
      - k8s/movies-depl.yaml
      - k8s/news-depl.yaml
      - k8s/secrets/movies-secret.yaml
portForward:
  - resourceType: service
    resourceName: index-srv
    namespace: z-dev
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: shl-client-srv
    namespace: z-dev
    port: 80
    localPort: 4000
  - resourceType: service
    resourceName: shl-api-srv
    namespace: z-dev
    port: 80
    localPort: 4001
  - resourceType: service
    resourceName: trivia-client-srv
    namespace: z-dev
    port: 80
    localPort: 5000
  - resourceType: service
    resourceName: trivia-api-srv
    namespace: z-dev
    port: 80
    localPort: 5001
  - resourceType: service
    resourceName: movies-srv
    namespace: z-dev
    port: 80
    localPort: 7000
  - resourceType: service
    resourceName: news-srv
    namespace: z-dev
    port: 80
    localPort: 8000
