apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: zetterstrom-dev
build:
  local:
    push: false
  artifacts:
    - image: viktorzetterstrom/index-zetterstrom-dev
      context: index
      sync:
        infer:
          - "**/*.html"
          - "**/*.js"
          - "**/*.css"
    - image: viktorzetterstrom/shl-client-zetterstrom-dev
      context: shl/client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: viktorzetterstrom/shl-api-zetterstrom-dev
      context: shl/api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/index-depl.yaml
      - k8s/shl-client-depl.yaml
      - k8s/shl-api-depl.yaml
      - k8s/secrets/shl-api-secret.yaml
portForward:
  - resourceType: service
    resourceName: index-srv
    namespace: z-dev
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: shl-client-srv
    namespace: z-dev
    port: 80
    localPort: 4000
  - resourceType: service
    resourceName: shl-api-srv
    namespace: z-dev
    port: 80
    localPort: 4001
