apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  namespace: z-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: zetterstrom.dev
      http:
        paths:
          - backend:
              serviceName: index-srv
              servicePort: 80
    - host: www.zetterstrom.dev
      http:
        paths:
          - backend:
              serviceName: index-srv
              servicePort: 80
    - host: shl.zetterstrom.dev
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: shl-api-srv
              servicePort: 80
          - path: /?(.*)
            backend:
              serviceName: shl-client-srv
              servicePort: 80
    - host: www.shl.zetterstrom.dev
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: shl-api-srv
              servicePort: 80
          - path: /?(.*)
            backend:
              serviceName: shl-client-srv
              servicePort: 80
