apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: z-dev-ingress
  namespace: z-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
    - host: zetterstrom.dev
      http:
        paths:
          - path: /?(.*)
            pathType: Exact
            backend:
              serviceName: index-srv
              servicePort: 80
    - host: shl.zetterstrom.dev
      http:
        paths:
          - path: /api/?(.*)
            pathType: Exact
            backend:
              serviceName: shl-api-srv
              servicePort: 80
          - path: /?(.*)
            pathType: Exact
            backend:
              serviceName: shl-client-srv
              servicePort: 80
    - host: trivia.zetterstrom.dev
      http:
        paths:
          - path: /api/?(.*)
            pathType: Exact
            backend:
              serviceName: trivia-api-srv
              servicePort: 80
          - path: /?(.*)
            pathType: Exact
            backend:
              serviceName: trivia-client-srv
              servicePort: 80
    - host: movies.zetterstrom.dev
      http:
        paths:
          - path: /?(.*)
            pathType: Exact
            backend:
              serviceName: movies-srv
              servicePort: 80
    - host: news.zetterstrom.dev
      http:
        paths:
          - path: /?(.*)
            pathType: Exact
            backend:
              serviceName: news-srv
              servicePort: 80
    - host: breathe.zetterstrom.dev
      http:
        paths:
          - path: /?(.*)
            pathType: Exact
            backend:
              serviceName: breathe-srv
              servicePort: 80
